name: Build Plugin Zip

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare plugin folder
        run: |
          mkdir gb-splide
          rsync -av --exclude=.git --exclude=.github --exclude=*.zip ./ gb-splide/

      - name: Create zip
        run: |
          cd gb-splide
          zip -r ../gb-splide.zip .

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: gb-splide.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}