name: Build Plugin Zip

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare plugin folder
        run: |
          PLUGIN_SLUG="gb-splide"
          BUILD_DIR="build"

          # Tạo thư mục tạm để build
          mkdir -p $BUILD_DIR/$PLUGIN_SLUG

          # Đồng bộ toàn bộ source code (trừ những thứ không cần thiết)
          rsync -av \
            --exclude=.git \
            --exclude=.github \
            --exclude=*.zip \
            --exclude=$BUILD_DIR \
            ./ $BUILD_DIR/$PLUGIN_SLUG/

      - name: Create zip with plugin folder inside
        run: |
          cd build
          zip -r ../gb-splide.zip gb-splide

      - name: Upload release asset to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: gb-splide.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}